# Normal (non-recovery) firmware Kconfig overrides.
# Applied on top of prj.conf when building with --variant=normal.

# Normal services.
CONFIG_SERVICE_ACTIVITY=y
CONFIG_SERVICE_ALARMS=y
CONFIG_SERVICE_APP_CACHE=y
CONFIG_SERVICE_APP_FETCH_ENDPOINT=y
CONFIG_SERVICE_APP_GLANCES=y
CONFIG_SERVICE_APP_INBOX_SERVICE=y
CONFIG_SERVICE_APP_MESSAGE=y
CONFIG_SERVICE_APP_ORDER_ENDPOINT=y
CONFIG_SERVICE_APP_OUTBOX_SERVICE=y
CONFIG_SERVICE_AUDIO_ENDPOINT=y
CONFIG_SERVICE_BLOB_DB=y
CONFIG_SERVICE_CONTACTS=y
CONFIG_SERVICE_DATA_LOGGING=y
CONFIG_SERVICE_FILESYSTEM=y
CONFIG_SERVICE_HEALTH_SYNC_ENDPOINT=y
CONFIG_SERVICE_MUSIC=y
CONFIG_SERVICE_NOTIFICATIONS=y
CONFIG_SERVICE_ORIENTATION_MANAGER=y
CONFIG_SERVICE_PERSIST=y
CONFIG_SERVICE_PHONE_CALL=y
CONFIG_SERVICE_POWERMODE_SERVICE=y
CONFIG_SERVICE_PROCESS_MANAGEMENT=y
CONFIG_SERVICE_PROTOBUF_LOG=y
CONFIG_SERVICE_SEND_TEXT_SERVICE=y
CONFIG_SERVICE_SERVICES_NORMAL=y
CONFIG_SERVICE_SETTINGS=y
CONFIG_SERVICE_SPEAKER=y
CONFIG_SERVICE_STATIONARY=y
CONFIG_SERVICE_TIMELINE=y
CONFIG_SERVICE_TIMEZONE_DATABASE=y
CONFIG_SERVICE_VIBES=y
CONFIG_SERVICE_VOICE_ENDPOINT=y
CONFIG_SERVICE_WAKEUP=y
CONFIG_SERVICE_WEATHER=y
