#
# Build rules for a Pebble application written in Embedded Swift.
#
import os.path

top = '.'
out = 'build'


def options(ctx):
    ctx.load('pebble_sdk')
    ctx.load('pebble_sdk_swift')


def configure(ctx):
    ctx.load('pebble_sdk')
    ctx.load('pebble_sdk_swift')


def build(ctx):
    ctx.load('pebble_sdk')
    ctx.load('pebble_sdk_swift')

    binaries = []
    cached_env = ctx.env
    for platform in ctx.env.TARGET_PLATFORMS:
        ctx.env = ctx.all_envs[platform]
        ctx.set_group(ctx.env.PLATFORM_NAME)
        app_elf = '{}/pebble-app.elf'.format(ctx.env.BUILD_DIR)
        ctx.pbl_build(source=ctx.path.ant_glob('src/c/**/*.c'),
                      swift_source=ctx.path.ant_glob('src/swift/**/*.swift'),
                      target=app_elf,
                      bin_type='app')
        binaries.append({'platform': platform, 'app_elf': app_elf})
    ctx.env = cached_env

    ctx.set_group('bundle')
    ctx.pbl_bundle(binaries=binaries,
                   js=ctx.path.ant_glob(['src/pkjs/**/*.js',
                                         'src/pkjs/**/*.json',
                                         'src/common/**/*.js']),
                   js_entry_file='src/pkjs/index.js')
