name: Release

on:
  push:
    tags:
      - v*

env:
  MEMFAULT_CLI_VERSION: "1.6.0"

jobs:
  build-prf:
    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/coredevices/pebbleos-docker:v5

    strategy:
      matrix:
        board:
          - asterix
          - obelix@dvt
          - obelix@pvt
          - getafix@evt
          - getafix@dvt
          - getafix@dvt2

    steps:
      - name: Mark Github workspace as safe
        run: git config --system --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true

      - name: Fetch tags
        run: |
          git fetch --tags --force

      - name: Install Python dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt

      - name: Set artifact board name
        id: artifact_board
        run: echo "NAME=$(printf '%s' "$BOARD" | tr @ _)" >> "$GITHUB_OUTPUT"
        env:
          BOARD: ${{ matrix.board }}

      - name: Configure
        run: ./waf configure --board '${{ matrix.board }}' --variant=prf -DCONFIG_RELEASE=y

      - name: Build PRF
        run: ./waf build

      - name: Bundle PRF
        run: ./waf bundle

      - name: Copy PRF artifacts
        run: |
          mkdir -p artifacts
          cp build/pebbleos.hex artifacts/prf_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}.hex
          cp build/pebbleos.bin artifacts/prf_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}.bin
          cp build/pebbleos.elf artifacts/prf_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}.elf
          cp build/*.pbz artifacts
          cp build/pebbleos_loghash_dict.json artifacts/prf_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}_loghash_dict.json

      - name: Get PRF Build ID
        id: prf_build_id
        run: |
          echo "BUILD_ID=$(readelf -n build/pebbleos.elf | sed -n -e 's/^.*Build ID: //p')" >> "$GITHUB_OUTPUT"

      - name: Upload PRF log hash dictionary
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LOG_HASH_BUCKET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LOG_HASH_BUCKET_SECRET }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          pip install awscli
          aws s3 cp build/pebbleos_loghash_dict.json \
            "s3://${{ vars.LOG_HASH_BUCKET_NAME }}/${{ steps.prf_build_id.outputs.BUILD_ID }}-${{ github.sha }}-prf.json" \
            --endpoint-url "${{ vars.LOG_HASH_BUCKET_ENDPOINT }}"

      - name: Configure PRF MFG
        run: ./waf configure --board '${{ matrix.board }}' --variant=prf -DCONFIG_MFG=y -DCONFIG_LOG_HASHED=n -DCONFIG_RELEASE=y

      - name: Build MFG PRF
        run: ./waf build

      - name: Copy MFG PRF artifacts
        run: |
          mkdir -p artifacts
          cp build/pebbleos.hex artifacts/prf_mfg_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}.hex
          cp build/pebbleos.bin artifacts/prf_mfg_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}.bin
          cp build/pebbleos.elf artifacts/prf_mfg_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}.elf

      - name: Store
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-prf-${{ steps.artifact_board.outputs.NAME }}
          path: artifacts

  build-firmware:
    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/coredevices/pebbleos-docker:v5

    strategy:
      matrix:
        board:
          - asterix
          - obelix@dvt
          - obelix@pvt
          - getafix@evt
          - getafix@dvt
          - getafix@dvt2
        slot:
          - 0
          - 1

        exclude:
          - board: "asterix"
            slot: 1

    steps:
      - name: Mark Github workspace as safe
        run: git config --system --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true

      - name: Fetch tags
        run: |
          git fetch --tags --force

      - name: Install Python dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Set artifact board name
        id: artifact_board
        run: echo "NAME=$(printf '%s' "$BOARD" | tr @ _)" >> "$GITHUB_OUTPUT"
        env:
          BOARD: ${{ matrix.board }}

      - name: Set slot suffix
        id: slot_suffix
        run: |
          NEEDS_SUFFIX="obelix_dvt obelix_pvt getafix_evt getafix_dvt getafix_dvt2"

          if echo $NEEDS_SUFFIX | grep -wq "${{ steps.artifact_board.outputs.NAME }}"; then
            echo "SLOT_SUFFIX=_slot${{ matrix.slot }}" >> "$GITHUB_OUTPUT"
          else
            echo "SLOT_SUFFIX=" >> "$GITHUB_OUTPUT"
          fi

      - name: Configure
        run: ./waf configure --board '${{ matrix.board }}' --slot ${{ matrix.slot }} -DCONFIG_RELEASE=y

      - name: Build firmware
        run: ./waf build

      - name: Bundle firmware
        run: ./waf bundle

      - name: Copy firmware artifacts
        run: |
          mkdir -p artifacts
          cp build/pebbleos.hex artifacts/firmware_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}${{ steps.slot_suffix.outputs.SLOT_SUFFIX }}.hex
          cp build/pebbleos.bin artifacts/firmware_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}${{ steps.slot_suffix.outputs.SLOT_SUFFIX }}.bin
          cp build/pebbleos.elf artifacts/firmware_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}${{ steps.slot_suffix.outputs.SLOT_SUFFIX }}.elf
          cp build/*.pbz artifacts
          cp build/pebbleos_loghash_dict.json artifacts/firmware_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}${{ steps.slot_suffix.outputs.SLOT_SUFFIX }}_loghash_dict.json

      - name: Get Build ID
        id: build_id
        run: |
          echo "BUILD_ID=$(readelf -n build/pebbleos.elf | sed -n -e 's/^.*Build ID: //p')" >> "$GITHUB_OUTPUT"

      - name: Upload log hash dictionary
        if: ${{ github.repository == 'coredevices/PebbleOS' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LOG_HASH_BUCKET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LOG_HASH_BUCKET_SECRET }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          pip install awscli
          aws s3 cp build/pebbleos_loghash_dict.json \
            "s3://${{ vars.LOG_HASH_BUCKET_NAME }}/${{ steps.build_id.outputs.BUILD_ID }}-${{ github.sha }}-normal.json" \
            --endpoint-url "${{ vars.LOG_HASH_BUCKET_ENDPOINT }}"

      - name: Store
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-${{ steps.artifact_board.outputs.NAME }}${{ steps.slot_suffix.outputs.SLOT_SUFFIX }}
          path: artifacts

      - name: Upload symbols to Memfault
        run: |
          pip install memfault-cli==${MEMFAULT_CLI_VERSION}

          memfault \
            --org-token ${{ secrets.MEMFAULT_ORG_TOKEN }} \
            --org ${{ secrets.MEMFAULT_ORG }} \
            --project ${{ secrets.MEMFAULT_PROJECT }} \
            upload-mcu-symbols \
            artifacts/firmware_${{ steps.artifact_board.outputs.NAME }}_${{github.ref_name}}${{ steps.slot_suffix.outputs.SLOT_SUFFIX }}.elf

  release:
    runs-on: ubuntu-24.04

    needs:
      - build-prf
      - build-firmware
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: Display artifacts
        run: ls -R

      - name: Merge slot-specific pbz files
        run: |
          NEEDS_MERGE="obelix_dvt obelix_pvt getafix_evt getafix_dvt getafix_dvt2"

          mkdir artifacts-merged
          for board in $NEEDS_MERGE; do
            python3 tools/merge_pbz.py \
              --slot0-pbz "artifacts-${board}_slot0/normal_${board}_${{ github.ref_name }}_slot0.pbz" \
              --slot1-pbz "artifacts-${board}_slot1/normal_${board}_${{ github.ref_name }}_slot1.pbz" \
              --output "artifacts-merged/normal_${board}_${{ github.ref_name }}.pbz"
          done

      - name: Create release
        uses: softprops/action-gh-release@v3.0.0
        with:
          files: artifacts-*/*

      - name: Deploy Memfault release
        run: |
          pip install memfault-cli==${MEMFAULT_CLI_VERSION}

          for file in artifacts-*/normal*.pbz; do
            # Skip slot-specific pbzs
            if echo $file | grep -q "_slot"; then
              continue
            fi

            BOARD=$(echo $file | sed -n -e 's/^.*normal_\([a-zA-Z0-9_]*\)_v.*\.pbz$/\1/p')

            memfault \
              --org-token ${{ secrets.MEMFAULT_ORG_TOKEN }} \
              --org ${{ secrets.MEMFAULT_ORG }} \
              --project ${{ secrets.MEMFAULT_PROJECT }} \
              upload-ota-payload \
              --hardware-version $BOARD \
              --software-type pebbleos \
              --software-version ${{ github.ref_name }} \
              $file
          done

          memfault \
            --org-token ${{ secrets.MEMFAULT_ORG_TOKEN }} \
            --org ${{ secrets.MEMFAULT_ORG }} \
            --project ${{ secrets.MEMFAULT_PROJECT }} \
            deploy-release \
            --release-version ${{ github.ref_name }} \
            --cohort internal
